[build-system]
requires = ["uv_build>=0.9.26,<0.13.0"]
build-backend = "uv_build"

[project]
name = "pj"
version = "0.0.0.dev0"
license = "GPL-2.0-or-later"
authors = [
  {name = "Matthias Dellweg"}
]
dependencies = [
  "click>=8.3.1,<8.5.1",
  "ipython>=9.9.0,<9.17.2",
  "jira>=3.10.5,<3.11.0",
  "pydantic>=2.12.5,<2.13.6",
]
classifiers = [
  "Private :: Do Not Upload",
]

[project.scripts]
pj = "pj:main"

[dependency-groups]
dev = [
    "ruff>=0.14.14,<0.15.0",
    "ty>=0.0.59",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["I"]
